config/routes.rb
Rails.application.routes.draw do
 
 root "todo_lists#index"
 # root  "welcome#show"
 resources :todo_lists do
   resources:todo_items
  end
 end
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  #belongs_to :todo_list
    #belongs_to :user
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    # has_many:todo_items,dependent: :destroy
    belongs_to :user
    
    validates :title, presence: true
    validates :description, presence: true
    validates :user, presence: true
    
    PRIORITIES = ['high', 'medium', 'low']
    CATEGORIES = ['Private','Work','Other']
    
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  
 has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
    before_action:set_todo_list
    
    def create
      @todo_item = @todo_list.todo_items.create(todo_item_params)
      redirect_to @todo_list
    end
end

def destroy
    @todo_item= @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy(params[:id])
        flash[:success]= "Todo List item was deleted."
    else
        flash[:error]= "Todo List item could not be deleted."
    end
#redirect_to @todo_list
respond_to do |format|
      format.html { redirect_to @todo_list }
      end
end
private

def set_todo_list 
    
 @todo_list=TodoList.find(params[:todo_list_id])  
end

def todo_item_params
    params[:todo_item].permit(:content)
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :require_login
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy, :clear]
  helper_method :sort_column, :sort_direction, :sort_column_category, :sort_column_priority, :sort_column_status, :sort_column_title, :sort_column_created_at
 
  # GET /todo_lists
  # GET /todo_lists.json
  def index 
   # @todo_lists = current_user.todo_lists
   @todo_lists = current_user.todo_lists.order("#{sort_column} #{sort_direction}")
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    
  end

  # GET /todo_lists/newcd 
  def new
     @todo_list = current_user.todo_lists.build 
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
   @todo_list = current_user.todo_lists.build(todo_list_params)
   @todo_list.user_id = current_user.id
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_lists_url, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_lists_url, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list= current_user.todo_lists.find(params[:id])
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo item was successfully deleted.' }
      format.json { head :no_content }
     # redirect_to todo_lists_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
       @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description,:duedate, :status, :category, :priority)
    end
    PRIORITIES=['High','Medium','Low']
    CATEGORIES=['Private','Work','Other']
    
    private
  def sortable_columns
    ["duedate","category","status", "priority", "title", "created_at", "description"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "duedate"
  end
  
  def sort_column_category
    sortable_columns.include?(params[:column]) ? params[:column] : "category"
  end
  
  def sort_column_status
    sortable_columns.include?(params[:column]) ? params[:column] : "status"
  end
  
  def sort_column_priority
    sortable_columns.include?(params[:column]) ? params[:column] : "priority"
  end
  
  def sort_column_title
    sortable_columns.include?(params[:column]) ? params[:column] : "title"
  end
  
  def sort_column_created_at
    sortable_columns.include?(params[:column]) ? params[:column] : "created_at"
  end
  
  def sort_column_description
    sortable_columns.include?(params[:column]) ? params[:column] : "description"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "bi bi-caret-down" : "bi bi-caret-up"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
    end
  
  def flash_class(level)
  bootstrap_alert_class = {
    "success" => "alert-success",
    "error" => "alert-danger",
    "notice" => "alert-info",
    "alert" => "alert-danger",
    "warn" => "alert-warning"
  }
  bootstrap_alert_class[level]
end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo WebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>

  <body>
<header>
     <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %> <br />
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
    </header>

    <section>
     <div id="flash">
      <% flash.each do |key, value| %>
        <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert"><%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
        </div>
      <% end %> 
    </div>
<%= yield %>
</section>
  </body>
</html>

app/views/todo_items/_todo_item.html.erb
<p><%= todo_item.content %></p>
<%= link_to  "Delete" ,todo_list_todo_item_path(@todo_list, todo_item.id),method: :delete,data: { confirm: "Are you sure?" } %>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" "form-group">
   
    <%= form.text_field :title, class:"form-control",placeholder:"Title" %>
  </div>

  <div class="field" "form-group">
   
    <%= form.text_area :description, class:"form-control",placeholder:"Description" %>
  </div>

<div class="field" "form-group">
   
    <%= form.date_select :duedate, class:"form-control",placeholder:"Due Date" %>
  </div>

  <div class="field" "form-group">
 
    <%= form.check_box :status,placeholder:"Status" %>
  </div>

  <div class="field" "form-group">
    
    <%= form.select :category, TodoListsController::CATEGORIES, class:"form-control",placeholder:"Category" %>
  </div>
  
  <div class="field" "form-group">
   
    <%= form.select :priority, TodoListsController::PRIORITIES, class:"form-control",placeholder:"Priority" %>
     
     
  </div>
  <br/>
  <div class="actions">
    <%= form.submit "Update ToDo Items", class:"btn btn-primary"%>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo Item</h1>
<br/>
<%= render 'form', todo_list: @todo_list %>


<%= link_to 'Back', todo_lists_path,class:"btn btn-warning" %>

app/views/todo_lists/index.html.erb
<h1><center><b>Todo Items</b></center></h1>

<br/>

<div id="wrapper">
  <div id="first"><%= link_to 'New Todo Item', new_todo_list_path, class:"btn btn-primary" %></div>
  <div id="second"><%= link_to "Clear Filters", todo_lists_path, class:"btn btn-secondary btn-sm"%></div>
</div>

<br/>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-light">
    <tr>
      <th>Done</th>
      <th><%= sort_link "title"%></th>
      <th><%= sort_link "description"%></th>
      <th><%= sort_link "duedate"%></th>
      <th><%= sort_link "category"%></th>
      <th><%= sort_link "priority"%></th>
      <th><%= sort_link "created_at"%></th>
      <th>Edit</th>
      <th>Delete</th>
      
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
    
      <% if todo_list.status %>
        <tr class="table-success">
          <td>
            <%= form_for(todo_list) do |f| %>
            <%= f.check_box :status, :checked => false, :style => 'visibility: hidden' %>
            <%= f.submit "Uncross" %>
            <% end %>
          </td>
          <td class="striker"><%= todo_list.title %></td>
          <td class="striker"><%= todo_list.description %></td>
          <td class="striker"><%= todo_list.duedate %></td>
          <td class="striker"><%= todo_list.category %></td>
          <td class="striker"><%= todo_list.priority %></td>
          <td class="striker"><%= todo_list.created_at.to_date %></td>
          <td>
            <center>
              <%= link_to edit_todo_list_path(todo_list), class:"btn btn-secondary" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
              <% end %>
            </center>
          </td>
          <td>
            <center>
              <%= link_to todo_list, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                </svg>
              <% end %>
            </center>
          </td>
        </tr>
      
      <% else %>
        <tr>
          <td>
            <%= form_for(todo_list) do |f| %>
            <%= f.check_box :status, :checked => true, :style => 'visibility: hidden' %>
            <%= f.submit "Check Off" %>
            <% end %>
          </td>
          <td><%= todo_list.title %></td>
          <td><%= todo_list.description %></td>
          <% if todo_list.duedate <= Date.today %>
            <td style="color:#dc3545"><%= todo_list.duedate %></td>
          <% else %>
            <td><%= todo_list.duedate %></td>
          <% end %>
          <td><%= todo_list.category %></td>
          <td><%= todo_list.priority %></td>
          <td><%= todo_list.created_at.to_date %></td>
          <td>
            <center>
              <%= link_to edit_todo_list_path(todo_list), class:"btn btn-secondary" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
              <% end %>
            </center>
          </td>
          <td>
            <center>
              <%= link_to todo_list, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                </svg>
              <% end %>
            </center>
          </td>
        </tr>
      
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/todo_lists/new.html.erb
<h1>New Todo Item</h1>
<br/>
<%= render 'form', todo_list: @todo_list %>
<br/>
<%= link_to 'Back', todo_lists_path,class:"btn btn-warning"%>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4"><%= @todo_list.title %> <%= @todo_list.description %> </h1>
  <p class="lead"><%= @todo_list.duedate %> | <%= @todo_list.status %>|<%= @todo_list.category %>
  |<%= @todo_list.priority %>
</p>
</p>
 
 <br/>
  
<%= link_to 'Edit', edit_todo_list_path(@todo_list), class: "btn btn-info" %> 
<%= link_to 'Back', todo_lists_path ,class: "btn btn-info"%>

  
</div>

app/views/welcome/show.html.erb
<h1>Welcome</h1>
<%= link_to 'My Todo Items', todo_lists_path %>